# Use the official Nginx image from DockerHub
FROM nginx

# Remove the default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy our configuration file to the Nginx conf.d directory
COPY nginx.conf /etc/nginx/conf.d/